# Generated by Django 4.0.3 on 2023-05-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('passwords', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('birth', models.DateField()),
            ],
        ),
    ]
